config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'
get 'jsonsource/zipsource'
 get "/home", to: "home#index", as: "home"
  get "/geocoding", to: "home#geocoding", as: "geocoding"
  get "/reverse_geocoding", to: "home#reverse_geocoding", as: "reverse_geocoding"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/geocoding.js.erb
$('#reverse_geocoding_fields').hide();
$('#geocoding_fields').show();
$('#geocoding').addClass('active');
$('#reverse_geocoding').removeClass('active');

app/views/home/index.html.erb
<script type="text/javascript">

$(document).ready(function(){
    $("#dtable").hide();
    $("#revealbutton").click(function(){

    if($(this).attr("value")=="What does this button do?"){

    this.value="Close the table";
    $(this).css('color','red');
       $.get("jsonsource/zipsource", function(data){

      		 
		for (var i = 0; i <100 ; i++)
	          {     
				
				if(i%2==0){

                      		var row = $("<tr class='even'>");
				}

				else{
				var row = $("<tr>");
				}

				 $("#zipcode").append(row);
				row.append($("<td>" + data[i].city + "</td>"));
				row.append($("<td>" + data[i].pop + "</td>"));
				row.append($("<td>" + data[i].state + "</td>"));
				row.append($("<td>" + data[i]._id + "</td>"));		
                      			 
                            	var row = $("</tr>");

				    
		  }
				
         $("#dtable").show();
	});
    }
	else{
 $("#dtable").hide();
this.value="What does this button do?"
$(this).css('color','green');
	}
   
    
	

    });

  
});

                         
                      

</script>
<div align="center">



<h1>Project 1</h1>
<p>This page displays json zip code data in a tabular form</p>

<input type="button" id="revealbutton" value="What does this button do?" style="color:green" name="button"/>
<table cellspacing='0' id="dtable">

	
	<thead>
		<tr>
			<th>City</th>
			<th>Population</th>
			<th>State</th>
<th>Zipcode</th>
		</tr>
	</thead>
	<tbody id="zipcode">

</tbody>


</table>



<h1>Google Maps Api</h1>

<div id="search_options">
  <%= link_to "Search using location", geocoding_path, remote: true, id: "geocoding"%>
  <%= link_to "Search using latitude and logitude", reverse_geocoding_path, remote: true, id: "reverse_geocoding"%>
</div>
<div id="map-container">
	<div id="map-canvas"></div>
 
  <div id="geocoding_fields">
    <%= text_field_tag :search, params[:search], placeholder: "Enter a place", :id => 'search_box_geocoding', class: 'search_box' %>
    <%= button_tag "Search", id: "submit_button_geocoding", data: { disable_with: "Please wait..." }, class: "submit_button" %> 
  </div>
  <div id="reverse_geocoding_fields">
    <%= text_field_tag :search, params[:search], placeholder: "Enter a point (latitude, longitude)", :id => 'search_box_reverse', class: 'search_box' %>
    <%= button_tag "Search", id: "submit_button_reverse", data: { disable_with: "Please wait..." }, class: "submit_button" %> 
  </div>
</div>
</div>

app/views/home/reverse_geocoding.js.erb
$('#geocoding_fields').hide();
$('#reverse_geocoding_fields').show();
$('#reverse_geocoding').addClass('active');
$('#geocoding').removeClass('active');